# Generated by Django 3.0.5 on 2020-04-14 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TennisUz', '0003_auto_20200414_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=models.ForeignKey(blank='TRUE', default=1, null='True', on_delete=django.db.models.deletion.SET_NULL, to='TennisUz.Hand'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_profy',
            field=models.BooleanField(default=False),
        ),
    ]
