# Generated by Django 3.0.5 on 2020-04-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TennisUz', '0004_auto_20200414_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'Місто', 'verbose_name_plural': 'Міста'},
        ),
    ]
