# Generated by Django 3.0.5 on 2020-04-23 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TennisUz', '0005_auto_20200414_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('pub_date', models.DateTimeField()),
                ('caption', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='backhand',
            options={'ordering': ('name',), 'verbose_name': 'Бекхенд', 'verbose_name_plural': 'Бекхенди'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('question',), 'verbose_name': 'Варіант відповіді', 'verbose_name_plural': 'Варіанти відповіді'},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ('name',), 'verbose_name': 'Корт', 'verbose_name_plural': 'Корти'},
        ),
        migrations.AlterModelOptions(
            name='covering',
            options={'ordering': ('name',), 'verbose_name': 'Покриття', 'verbose_name_plural': 'Покриття'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-set',), 'verbose_name': 'Гейм', 'verbose_name_plural': 'Гейми'},
        ),
        migrations.AlterModelOptions(
            name='game_log',
            options={'ordering': ('-game',), 'verbose_name': 'Хід гри', 'verbose_name_plural': 'Хід гри'},
        ),
        migrations.AlterModelOptions(
            name='hand',
            options={'ordering': ('name',), 'verbose_name': 'Покриття', 'verbose_name_plural': 'Покриття'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-dt',), 'verbose_name': 'Матч', 'verbose_name_plural': 'Матчі'},
        ),
        migrations.AlterModelOptions(
            name='match_type',
            options={'ordering': ('name',), 'verbose_name': 'Тип матчу', 'verbose_name_plural': 'Типи матчів'},
        ),
        migrations.AlterModelOptions(
            name='myimage',
            options={'ordering': ('-dt',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_name', 'second_name'), 'verbose_name': 'Фізична особа', 'verbose_name_plural': 'Фізичні особи'},
        ),
        migrations.AlterModelOptions(
            name='place_court',
            options={'ordering': ('name',), 'verbose_name': 'Частина корту', 'verbose_name_plural': 'Частини корту'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('person',), 'verbose_name': 'Гравець', 'verbose_name_plural': 'Гравці'},
        ),
        migrations.AlterModelOptions(
            name='player_rank',
            options={'ordering': ('-dt',), 'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Питання', 'verbose_name_plural': 'Питання'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',), 'verbose_name': 'Регіон', 'verbose_name_plural': 'Регіони'},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ('-match',), 'verbose_name': 'Сет', 'verbose_name_plural': 'Сети'},
        ),
        migrations.AlterModelOptions(
            name='shot_hand',
            options={'ordering': ('name',), 'verbose_name': 'Удар', 'verbose_name_plural': 'Удари'},
        ),
        migrations.AlterModelOptions(
            name='shot_type',
            options={'ordering': ('name',), 'verbose_name': 'Тип удару', 'verbose_name_plural': 'Типи ударів'},
        ),
        migrations.AlterModelOptions(
            name='stadium',
            options={'ordering': ('name',), 'verbose_name': 'Стадіон', 'verbose_name_plural': 'Стадіони'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Тег'},
        ),
        migrations.AlterModelOptions(
            name='torney_group_name',
            options={'ordering': ('name',), 'verbose_name': 'Турнірна група(назва)', 'verbose_name_plural': 'Турнірні групи(назва)'},
        ),
        migrations.AlterModelOptions(
            name='torney_group_player',
            options={'ordering': ('tourney_group', 'player'), 'verbose_name': 'Гравець турніру', 'verbose_name_plural': 'Гравці турніру'},
        ),
        migrations.AlterModelOptions(
            name='torney_round',
            options={'ordering': ('name',), 'verbose_name': 'Раунд', 'verbose_name_plural': 'Раунди'},
        ),
        migrations.AlterModelOptions(
            name='tourney',
            options={'ordering': ('-dt',), 'verbose_name': 'Турнір', 'verbose_name_plural': 'Турніри'},
        ),
        migrations.AlterModelOptions(
            name='tourney_group',
            options={'ordering': ('name',), 'verbose_name': 'Турнірна група', 'verbose_name_plural': 'Турнірні групи'},
        ),
        migrations.AlterModelOptions(
            name='winner_type',
            options={'ordering': ('name',), 'verbose_name': 'Тип виграшу', 'verbose_name_plural': 'Типи виграшів'},
        ),
        migrations.AddField(
            model_name='myimage',
            name='dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourney',
            name='dt',
            field=models.DateField(blank='True', null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='player',
            name='backhand',
            field=models.ForeignKey(blank='TRUE', default=1, null='True', on_delete=django.db.models.deletion.SET_NULL, to='TennisUz.Backhand'),
        ),
        migrations.CreateModel(
            name='Order_court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_start', models.DateTimeField(verbose_name='Дата початку')),
                ('d_fin', models.DateTimeField(verbose_name='Дата завершення')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TennisUz.Court')),
                ('player', models.ForeignKey(blank='TRUE', null='True', on_delete=django.db.models.deletion.SET_NULL, to='TennisUz.Player')),
            ],
            options={
                'verbose_name': 'Замовлення корту',
                'verbose_name_plural': 'Замовлення корту',
                'ordering': ('-d_start',),
            },
        ),
    ]
